port: 3000
user: hiscore
group: hiscore
pid: tmp/pids/thin.pid
timeout: 30
wait: 30
log: log/thin.log
max_conns: 1024
require: []
environment: production
max_persistent_conns: 512
servers: 1
threaded: false
no-epoll: true
daemonize: true
chdir: /home/hiscore/hsctm_test
tag: hsctm_test